"""BMI table

Revision ID: 949097ca1236
Revises: 9c84a968187c
Create Date: 2022-05-11 10:56:36.572044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949097ca1236'
down_revision = '9c84a968187c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BMI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BMI_label', sa.String(length=140), nullable=True),
    sa.Column('BMI_predicted', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BMI_timestamp'), 'BMI', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BMI_timestamp'), table_name='BMI')
    op.drop_table('BMI')
    # ### end Alembic commands ###
